"""Stable public facade for notebooks and external experiment drivers.

Importing this module loads only contracts and dependency-free helpers.
``LocalNotebookPlatform`` loads the executable implementations (Stim, PyTorch,
PyMatching) when it is constructed.
"""

from ai_qec.config_validation import (
    ConfigurationError,
    MissingConfigurationError,
    UnresolvedConfigurationError,
    build_from_config,
    find_unresolved,
    get_config_path,
    validate_config,
    validate_no_unresolved,
    validate_registered_selections,
)
from ai_qec.data.datasets.local import DatasetIntegrityError
from ai_qec.data.datasets import (
    DatasetArtifact,
    DatasetIdentityProvider,
    DatasetInstance,
    DatasetKey,
    DatasetRegistry,
    DatasetResolution,
    DatasetResolver,
    DatasetRole,
    DatasetSpec,
    DatasetSplit,
)
from ai_qec.data.generators import GeneratorDevice, QECDataGenerator, SyndromeGeneratorDescriptor
from ai_qec.data.pipeline import (
    CPUToGPUDataPipeline,
    CPUToGPUPipelineSpec,
    GPUToGPUDataPipeline,
    GPUToGPUPipelineSpec,
    TransferEvidence,
)
from ai_qec.data.schema import BatchLayout, BatchRepresentation, MemoryResidency, QECBatch
from ai_qec.evaluation.scientific.local import AccuracyGateError, EvaluationError
from ai_qec.evaluation.scientific.statistics import paired_difference_interval, wilson_interval
from ai_qec.evaluation.scientific import (
    AccuracyGate,
    AccuracyGateSpec,
    DecoderEvaluation,
    GateDecision,
    MetricEstimate,
    ScientificAcceptanceResult,
    ScientificEvaluationResult,
    ScientificEvaluationSpec,
    ScientificEvaluator,
)
from ai_qec.experiment.grid import GridPoint, config_grid, with_overrides
from ai_qec.experiment.local import AttemptInProgressError, AttemptStateError
from ai_qec.experiment import (
    ArtifactKind,
    ArtifactManifest,
    ArtifactRef,
    ArtifactRepository,
    Attempt,
    AttemptStatus,
    Experiment,
    ExperimentFactory,
    ExperimentSpec,
    RandomStreamDescriptor,
    RandomStreams,
    RecoveryPlan,
    RecoverySource,
    StageRecord,
    StageRecorder,
    StageStatus,
)
from ai_qec.models import ModelSpec
from ai_qec.models.decoders import (
    DecodeRequest,
    DecodeResult,
    DecodeStatus,
    Decoder,
    DecoderRuntimeDescriptor,
)
from ai_qec.paper import NotebookExperiment, NotebookPlatform, NotebookRun
from ai_qec.paper.local_runtime import LocalNotebookPlatform
from ai_qec.qec import NoiseApproximation, NoiseCompilation, NoiseCompiler, NoiseSpec, QECSpec
from ai_qec.qec.backends import BackendCompatibility, QECBackend
from ai_qec.qec.circuits import CircuitBuildResult, QECCircuitAdapter
from ai_qec.registries import (
    CIRCUITS,
    CODES,
    CPU_TO_GPU_PIPELINES,
    DECODERS,
    GENERATORS,
    GPU_TO_GPU_PIPELINES,
    LOSSES,
    MODELS,
    NOISE,
    NOISE_ADAPTERS,
    OPTIMIZERS,
    REGISTRIES_BY_PATH,
    SCHEDULERS,
    TRAINERS,
    TRAINING_STEP_EXECUTORS,
)
from ai_qec.registry import (
    DuplicateRegistrationError,
    Registry,
    RegistryError,
    UnknownRegistrationError,
)
from ai_qec.reporting.figures import (
    SweepPoint,
    figure_png,
    plot_decoder_comparison,
    plot_failure_rate_sweep,
    plot_logical_class_histograms,
    plot_logical_classes,
    plot_training_history,
)
from ai_qec.technology import TechnologyId, TechnologyImplementation
from ai_qec.training.execution_planner import ExecutionConfigurationError
from ai_qec.utils.paths import find_project_root
from ai_qec.training import (
    ExecutionPlanner,
    ExecutionSpec,
    ResolvedExecutionPlan,
    Trainer,
    TrainingSpec,
    BatchSignature,
    BatchSignatureEvidence,
    TensorSignature,
    TrainingStepContext,
    TrainingStepEvidence,
    TrainingStepExecutor,
    TrainingStepPlan,
    TrainingStepResult,
)
from ai_qec.training.checkpoint import ModelCheckpoint, TrainingRecoveryCheckpoint

__all__ = [
    "AccuracyGate",
    "AccuracyGateError",
    "AttemptInProgressError",
    "AttemptStateError",
    "DatasetIntegrityError",
    "EvaluationError",
    "ExecutionConfigurationError",
    "LocalNotebookPlatform",
    "SweepPoint",
    "config_grid",
    "figure_png",
    "find_project_root",
    "GridPoint",
    "with_overrides",
    "paired_difference_interval",
    "plot_decoder_comparison",
    "plot_failure_rate_sweep",
    "plot_logical_class_histograms",
    "plot_logical_classes",
    "plot_training_history",
    "wilson_interval",
    "AccuracyGateSpec",
    "ArtifactKind",
    "ArtifactManifest",
    "ArtifactRef",
    "ArtifactRepository",
    "Attempt",
    "AttemptStatus",
    "BackendCompatibility",
    "BatchLayout",
    "BatchRepresentation",
    "BatchSignature",
    "BatchSignatureEvidence",
    "CIRCUITS",
    "CODES",
    "CPUToGPUDataPipeline",
    "CPUToGPUPipelineSpec",
    "CPU_TO_GPU_PIPELINES",
    "CircuitBuildResult",
    "ConfigurationError",
    "DECODERS",
    "DatasetArtifact",
    "DatasetIdentityProvider",
    "DatasetInstance",
    "DatasetKey",
    "DatasetRegistry",
    "DatasetResolution",
    "DatasetResolver",
    "DatasetRole",
    "DatasetSpec",
    "DatasetSplit",
    "DecodeRequest",
    "DecodeResult",
    "DecodeStatus",
    "Decoder",
    "DecoderEvaluation",
    "DecoderRuntimeDescriptor",
    "DuplicateRegistrationError",
    "ExecutionSpec",
    "ExecutionPlanner",
    "Experiment",
    "ExperimentFactory",
    "ExperimentSpec",
    "GateDecision",
    "GENERATORS",
    "GPUToGPUDataPipeline",
    "GPUToGPUPipelineSpec",
    "GPU_TO_GPU_PIPELINES",
    "GeneratorDevice",
    "LOSSES",
    "MODELS",
    "MetricEstimate",
    "MissingConfigurationError",
    "ModelCheckpoint",
    "ModelSpec",
    "NoiseApproximation",
    "NoiseCompilation",
    "NoiseCompiler",
    "NoiseSpec",
    "NOISE",
    "NOISE_ADAPTERS",
    "NotebookExperiment",
    "NotebookPlatform",
    "NotebookRun",
    "OPTIMIZERS",
    "QECBackend",
    "QECBatch",
    "QECDataGenerator",
    "QECCircuitAdapter",
    "QECSpec",
    "RandomStreamDescriptor",
    "RandomStreams",
    "REGISTRIES_BY_PATH",
    "Registry",
    "RegistryError",
    "RecoveryPlan",
    "RecoverySource",
    "ResolvedExecutionPlan",
    "ScientificAcceptanceResult",
    "ScientificEvaluationResult",
    "ScientificEvaluationSpec",
    "ScientificEvaluator",
    "SCHEDULERS",
    "StageRecord",
    "StageRecorder",
    "StageStatus",
    "SyndromeGeneratorDescriptor",
    "TechnologyId",
    "TechnologyImplementation",
    "TensorSignature",
    "TRAINERS",
    "TRAINING_STEP_EXECUTORS",
    "Trainer",
    "TransferEvidence",
    "TrainingRecoveryCheckpoint",
    "TrainingSpec",
    "TrainingStepContext",
    "TrainingStepEvidence",
    "TrainingStepExecutor",
    "TrainingStepPlan",
    "TrainingStepResult",
    "UnknownRegistrationError",
    "UnresolvedConfigurationError",
    "build_from_config",
    "find_unresolved",
    "get_config_path",
    "validate_config",
    "validate_no_unresolved",
    "validate_registered_selections",
    "MemoryResidency",
]
